name: Deploy to GitHub Pages

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create Firebase Config
        run: |
          cat << EOF > firebase-config.js
          const firebaseConfig = ${{ secrets.FIREBASE_CONFIG }};

          // Importera funktioner från Firebase SDKs
          import { initializeApp } from 'https://www.gstatic.com/firebasejs/10.12.2/firebase-app.js';
          import { getAuth } from 'https://www.gstatic.com/firebasejs/10.12.2/firebase-auth.js';
          import { getFirestore } from 'https://www.gstatic.com/firebasejs/10.12.2/firebase-firestore.js';
          import { getStorage } from 'https://www.gstatic.com/firebasejs/10.12.2/firebase-storage.js';

          // Initiera Firebase
          const app = initializeApp(firebaseConfig);

          // Exportera de tjänster vi kommer att använda i andra filer
          export const auth = getAuth(app);
          export const db = getFirestore(app);
          export const storage = getStorage(app);
          EOF

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
